### ISSUE TITLE
ros_comm/rosbag on Windows

### ISSUE THREAD

**Issue by gavanderhoorn** [rospypi/simple#3]
Following the instructions on Windows (7 in this case, but I don't believe that matters) and installing `rosbag` leads to import errors complaining about `Cryptodome` and `gnupg`. Somehow `pip` did not pick up on those being needed.

Installing them (using `pip install pycryptodomex gnupg` made things work.

(note: installing `pycryptodome` is not enough, as it doesn't place the module/package in the expected directory)

**Comment by otamachan** [comment]
Thank you for your feedback!

The reason why it lacks the necessary dependencies is that the original package itself [does not have those depedencies](https://github.com/ros/ros_comm/blob/d9059f49d14b7baf4a58c7759deab1f019681f5b/tools/rosbag/setup.py#L10). So as you mentioned it's not related to Windows.
Other packages such as [rospy](), [roslib](https://github.com/ros/ros/blob/2b307e1854ebf3954a5b4110f891278f555e79a6/core/roslib/setup.py#L9) also do not have right dependencies. (Maybe it's because the catkin resolves those dependencies.)

But I modified the builder so that it can inject those dependencies during the package build without changing the original source, so it's now fixable.
I released the newer version of rosbag([1.14.3.post0](https://rospypi.github.io/simple/rosbag/)) which have the right dependencies.

Please try if you have time. (`pip install --extra-index-url https://rospypi.github.io/simple rosbag` will install `pycryptodomex`, `gnupg`, `rospy`, etc )

**Comment by gavanderhoorn** [comment]
Those dependencies are indeed listed in the package manifest of `rosbag` ([here](https://github.com/ros/ros_comm/blob/d9059f49d14b7baf4a58c7759deab1f019681f5b/tools/rosbag/package.xml#L40-L43)).

I'm not entirely sure what the rationale is for listing some dependencies in the manifest and others in `setup.py`.

Perhaps your builder could inspect the `package.xml` as well?

And thanks for the fix. I'll see whether I can test it sometime this week.

**Comment by otamachan** [comment]
> Perhaps your builder could inspect the package.xml as well?

Maybe.
The dependencies in `package.xml` are listed in apt package name and it's sometimes different from Python package name in pypi, which makes a bit difficult to use it now.(e.g. [`python-yaml`](https://packages.ubuntu.com/ja/xenial/python-yaml) vs [`pyyaml`](https://pypi.org/project/PyYAML/)).
So I listed it manually now(https://github.com/rospypi/simple/blob/master/packages.yaml#L69-L73), but it could be improved.

**Comment by gavanderhoorn** [comment]
`python-yaml` is the `rosdep` key name. See [here](https://github.com/ros/rosdistro/blob/66477d266e60648186e86438fb700efa151f6e1a/rosdep/python.yaml#L4996).

**Comment by otamachan** [comment]
Ah yes, but it does not seem always offer pip key?

**Comment by gavanderhoorn** [comment]
No, the `pip` keys is almost never used actually. As releasing `.deb` packages cannot work when depending on `pip` keys.

I wouldn't know a way around that.

**Comment by gavanderhoorn** [comment]
As I believe you've fixed this, I'm closing this issue.

Thanks for the quick response.
