### ISSUE TITLE
Collaboration with RoboStack project?

### ISSUE THREAD

**Issue by Tobias-Fischer** [rospypi/simple#47]
Hi there,

This project looks very interesting, great work! I just came across it by chance. Do you happen to know our [RoboStack](https://github.com/RoboStack/ros-noetic) project? It offers ROS packages based on Conda, so similar to your project you can install ROS packages in a conda virtual environment. It would be great to have a chat if/how we can join forces :).

Best, Tobias

/cc @wolfv @traversaro

**Comment by otamachan** [comment]
Thank you very much for your interest in this project.
I know about RoboStack from Discourse of course, and I think it's a great project that covers many of the ROS packages including RViz etc.

I believe it would be nice to combine efforts that provide a similar ecosystem. Since rospypi/simple focuses only on Python packages for now and uses `setuptools` as a build tool, I don't have much idea on how we can collaborate at the moment. 
Do you have any concreate ideas on how we can collaborate in mind?

Best regards,
Tamaki

**Comment by Tobias-Fischer** [comment]
Hi Tamaki,

Many thanks for your response! Indeed it seems like your repo and RoboStack are complementary: you offer a very lightweight way of installing some pure Python ROS packages via pip, whereas RoboStack aims to offer a more complete set of ROS packages including C++ ones but requires using conda.

I'd be very happy to include a reference to your repo as an alternative to RoboStack in the RoboStack readme - if you do the same it might increase the visibility of both repos. What do you think?

@traversaro @wolfv - do you have any suggestions?

Best, TObias

**Comment by otamachan** [comment]
Hi, Tobias!

Sorry for my late response and thank you for your proposal!
> I'd be very happy to include a reference to your repo as an alternative to RoboStack in the RoboStack readme

I think that's a good idea.

I'll update the README soon!
