### ISSUE TITLE
How to start roscore?

### ISSUE THREAD

**Issue by Ever-OvO** [rospypi/simple#67]
How can I start roscore?This problem bothered me for a long time.

**Comment by Ever-OvO** [comment]
I want to start roscore from a Linux terminal and then communicate with windows. How can I do this?

**Comment by bonprosoft** [comment]
Hi @Ever-OvO ,

Let me clarify.

- If you are not sure how to launch the official `roscore`, please refer to the official document
  -  For newbies, it's a common mistake to forget running `source /opt/ros/foxy/setup.bash` before launching the roscore.
  - http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment#Managing_Your_Environment
- If you are not sure how to launch an unofficial `roscore` using the `rospypi`, refer to this issue: https://github.com/rospypi/simple/issues/62
  - IMHO, I don't recommend to use our system to host the roscore. Our main target is to provide a handy way for Python users who want to build a ROS environment on a virtualenv. (i.e. basically we focus on ROS nodes, not either the roscore or the whole ROS stack.)
  - Since `roscore` itself is a stand-alone application, I recommend you to use a docker image instead: https://hub.docker.com/_/ros

**Comment by Ever-OvO** [comment]
> Hi @Ever-OvO ,
> 
> Let me clarify.
> 
> * If you are not sure how to launch the official `roscore`, please refer to the ROS official document
>   
>   * This repository is NOT official as written in our README
>   * For newbies, it's a common mistake to forget running `source /opt/ros/foxy/setup.bash` before launching the roscore.
>   * http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment#Managing_Your_Environment
> * If you are not sure how to launch an unofficial `roscore` using the `rospypi`, refer to this issue: [Is it possible to start a roscore using rospypi from Python code? #62](https://github.com/rospypi/simple/issues/62)
>   
>   * IMHO, I don't recommend to use our system to host the roscore. Our main target is to provide a handy way for Python users who want to build a ROS environment on a virtualenv. (i.e. basically we focus on ROS nodes, not either the roscore or the whole ROS stack.)
>   * Since `roscore` itself is a stand-alone application, I recommend you to use a docker image instead: https://hub.docker.com/_/ros

Thanks a lot. I have solved the problem by ssh.
