### ISSUE TITLE
Wrong mapping in `_CV_TYPES`?

### ISSUE THREAD

**Issue by SuperN1ck** [rospypi/simple#70]
Hey!

thanks for this awesome repo!

I had problems converting a `16UC1` depth image with `cv_bridge` installed through this repo. I am using it like
```
frame = cv_bridge_instance.imgmsg_to_cv2(
    ros_image, desired_encoding="passthrough"
) 
````

Luckily, I could track down the issue to a wrongly initialized dict here:
https://github.com/rospypi/simple/blob/998c360810767c48733b278e36f90c5fa56d1e0c/cv_bridge/python/cv_bridge/boost/cv_bridge_boost.py#L22
I changed this and the following 4 lines to
```
"16UC1": cv2.CV_16UC1,
"16UC2": cv2.CV_16UC1,
"16UC3": cv2.CV_16UC1,
"16UC4": cv2.CV_16UC1,
```
and now the above call returns the correct depth image.

About fixing the issue, I couldn't pin down whether this is a auto-generated file or manually and whether this is a bug in this repo or the original https://github.com/ros-perception/vision_opencv/tree/rolling/cv_bridge
But I would assume these regex are somewhat related: 
https://github.com/ros-perception/vision_opencv/blob/c620dd9210bae632ebb442a63f34e9e0d469c57b/cv_bridge/src/cv_bridge.cpp#L106

Thanks,
-Nick

**Comment by otamachan** [comment]
Thank you for your report.

`cv_bridge.getCvType` is originally exported [here](https://github.com/ros-perception/vision_opencv/blob/08b012c038e575d7fe1d538f11235a994159dc93/cv_bridge/python/cv_bridge/__init__.py#L6) and it's implemented [here](https://github.com/ros-perception/vision_opencv/blob/08b012c038e575d7fe1d538f11235a994159dc93/cv_bridge/src/module.cpp#L93) and [here](https://github.com/ros-perception/vision_opencv/blob/08b012c038e575d7fe1d538f11235a994159dc93/cv_bridge/src/cv_bridge.cpp#L72) in c++.
In order to avoid building c++ code, I implemented the same functionality in Python. So yes, this is a bug in this repository.

I'd appreciate it if you could send me a pull request if you need it fixed soon.

**Comment by otamachan** [comment]
Thank you for your PR! I think I could release a newer vesrion of `cv_bridge`. Could you check it? https://github.com/rospypi/simple/raw/any/cv-bridge/cv_bridge-1.13.0.post1-py2.py3-none-any.whl
